package com.tomasrepcik.blumodify.app.ui

object AppTestTags {


    const val APP_DRAWER_BUTTON = "APP_DRAWER_BUTTON"
    const val APP_DRAWER_SHEET = "APP_DRAWER_SHEET"
    const val APP_DRAWER_SHEET_HOME = "APP_DRAWER_HOME"
    const val APP_DRAWER_SHEET_SETTINGS = "APP_DRAWER_SETTINGS"
    const val APP_DRAWER_SHEET_ABOUT = "APP_DRAWER_ABOUT"

    const val APP_BACK_BUTTON = "APP_BACK_BUTTON"

    const val APP_ERROR_SCREEN = "APP_ERROR_SCREEN"
    const val APP_ERROR_SCREEN_DETAIL = "APP_ERROR_SCREEN_DETAIL"
    const val APP_ERROR_SCREEN_BUTTON_DETAIL = "APP_ERROR_SCREEN_BUTTON_DETAIL"
    const val APP_ERROR_SCREEN_BUTTON_PRIMARY = "APP_ERROR_SCREEN_BUTTON_PRIMARY"
    const val APP_ERROR_SCREEN_BUTTON_SECONDARY = "APP_ERROR_SCREEN_BUTTON_SECONDARY"
    const val APP_ERROR_SCREEN_BUTTON_DETAIL_BACK = "APP_ERROR_SCREEN_BUTTON_DETAIL_BACK"
    const val APP_ERROR_SCREEN_BUTTON_DETAIL_MAIL = "APP_ERROR_SCREEN_BUTTON_DETAIL_MAIL"

}