package com.tomasrepcik.blumodify.settings

object SettingsTestTags {

    const val SETTINGS_SCREEN = "SETTINGS_SCREEN"


    // LOGS
    const val LOG_DETAIL = "LOG_DETAIL"
    const val LOG_DETAIL_TIME = "LOG_DETAIL_TIME"
    const val LOG_DETAIL_STATUS = "LOG_DETAIL_STATUS"
    const val LOG_DETAIL_DEVICES = "LOG_DETAIL_DEVICES"
    const val LOG_DETAIL_STACKTRACE = "LOG_DETAIL_STACKTRACE"


    // ADVANCED
    const val ADVANCED_LIST_SCREEN = "ADVANCED_LIST_SCREEN"
    const val ADVANCED_BT_PICKER_SCREEN = "ADVANCED_BT_PICKER_SCREEN"

    const val ADVANCED_LIST_TO_DELETE = "ADVANCED_LIST_TO_DELETE"
    const val ADVANCED_ADD_DEVICE_BUTTON = "ADVANCED_ADD_DEVICE_BUTTON"

    const val ADVANCED_BT_OFF_SCREEN = "ADVANCED_BT_OFF_SCREEN"
    const val ADVANCED_TURN_ON_BT_BUTTON = "ADVANCED_TURN_ON_BT_BUTTON"
    const val ADVANCED_NO_PAIRED_DEVICES_SCREEN = "ADVANCED_NO_PAIRED_DEVICES_SCREEN"
    const val ADVANCED_ALL_PAIRED_DEVICES_ADDED_SCREEN = "ADVANCED_ALL_PAIRED_DEVICES_ADDED_SCREEN"
    const val ADVANCED_MISSING_BT_PERMISSION = "ADVANCED_MISSING_BT_PERMISSION"
    const val ADVANCED_BT_PICKER_LIST = "ADVANCED_BT_PICKER_LIST"


}