plugins {
    alias libs.plugins.android.application
    alias libs.plugins.ksp
    alias libs.plugins.hilt
    alias libs.plugins.kotlin.compose
    alias libs.plugins.kotlin.serialization
    alias libs.plugins.oss.licenses
}

android {
    namespace = "com.tomasrepcik.blumodify"
    compileSdk = 37
    ndkVersion = "21.1.6352462"

    defaultConfig {
        applicationId = "com.tomasrepcik.blumodify"
        minSdk = 27
        targetSdk = 37
        versionCode = 1
        versionName = "1.0.0"

        testInstrumentationRunner = "com.tomasrepcik.blumodify.runner.HiltRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.debug
            minifyEnabled = false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig = true
        compose = true
    }
    packagingOptions {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "/META-INF/LICENSE.md"
            excludes += "/META-INF/LICENSE-notice.md"
        }
    }
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
}

dependencies {
    // hilt
    implementation libs.hilt.android
    ksp libs.hilt.compiler
    implementation libs.androidx.hilt.navigation.compose

    // navigation
    implementation libs.androidx.navigation.compose

    // data storage
    implementation libs.androidx.datastore
    implementation libs.kotlinx.serialization.json

    // android core
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.activity.compose
    implementation libs.androidx.compose.material

    // UI
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.material3
    implementation libs.androidx.core.splashscreen
    implementation libs.androidx.tracing

    // workmanager
    implementation libs.androidx.hilt.work
    ksp libs.androidx.hilt.compiler
    implementation libs.androidx.work.runtime.ktx

    // room
    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler

    // rive
    implementation libs.rive.android
    implementation libs.androidx.startup

    // google play licenses
    implementation libs.play.services.oss.licenses

    // google play update
    implementation libs.play.app.update.ktx

    // TESTING

    // core
    testImplementation libs.junit

    // third parties
    testImplementation libs.kotlinx.coroutines.test
    testImplementation libs.mockito.core
    testImplementation libs.mockito.kotlin
    testImplementation libs.mockk
    testImplementation libs.turbine
    
    // instrumentation testing
    androidTestImplementation libs.androidx.test.monitor
    androidTestImplementation libs.androidx.test.junit.ktx
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.androidx.test.rules
    androidTestImplementation libs.mockito.android
    androidTestImplementation libs.mockito.kotlin

    // compose
    androidTestImplementation libs.androidx.compose.ui.test.junit4
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest

    // test manager
    androidTestImplementation libs.androidx.work.testing

    // hilt
    androidTestImplementation libs.hilt.android.testing
    kspAndroidTest libs.hilt.compiler

    // room
    testImplementation libs.androidx.room.testing
    implementation libs.androidx.room.paging
}
