package com.tomasrepcik.blumodify.intro

object IntroTestTags {


    const val INTRO_WELCOME_SCREEN = "WELCOME_SCREEN"
    const val INTRO_RECOMMENDATION_SCREEN = "RECOMMENDATION_SCREEN"
    const val INTRO_MOTIVATION_PRIVACY_SCREEN = "MOTIVATION_PRIVACY_SCREEN"
    const val INTRO_MOTIVATION_ENERGY_SCREEN = "MOTIVATION_ENERGY_SCREEN"
    const val INTRO_BATTERY_OPTIMISATION_SCREEN = "BATTERY_OPTIMISATION_SCREEN"

    val INTRO_SCREENS = arrayOf(
        INTRO_WELCOME_SCREEN,
        INTRO_RECOMMENDATION_SCREEN,
        INTRO_MOTIVATION_PRIVACY_SCREEN,
        INTRO_MOTIVATION_ENERGY_SCREEN,
        INTRO_BATTERY_OPTIMISATION_SCREEN,
    )

    // BUTTONS
    const val INTRO_WELCOME_SCREEN_NEXT_BUTTON = "INTRO_WELCOME_SCREEN_NEXT_BUTTON"
    const val INTRO_RECOMMENDATION_SCREEN_NEXT_BUTTON = "INTRO_RECOMMENDATION_SCREEN_NEXT_BUTTON"
    const val INTRO_MOTIVATION_PRIVACY_SCREEN_NEXT_BUTTON = "INTRO_MOTIVATION_PRIVACY_SCREEN_NEXT_BUTTON"
    const val INTRO_MOTIVATION_ENERGY_SCREEN_NEXT_BUTTON = "INTRO_MOTIVATION_ENERGY_SCREEN_NEXT_BUTTON"
    const val INTRO_BATTERY_OPTIMISATION_SCREEN_ENLIST_BUTTON = "INTRO_BATTERY_OPTIMISATION_SCREEN_ENLIST_BUTTON"
    const val INTRO_BATTERY_OPTIMISATION_SCREEN_START_BUTTON = "INTRO_BATTERY_OPTIMISATION_SCREEN_START_BUTTON"


}