package com.tomasrepcik.blumodify.intro

object IntroTestTags {

    // BUTTONS
    const val INTRO_WELCOME_SCREEN_NEXT_BUTTON = "INTRO_WELCOME_SCREEN_NEXT_BUTTON"
    const val INTRO_RECOMMENDATION_SCREEN_NEXT_BUTTON = "INTRO_RECOMMENDATION_SCREEN_NEXT_BUTTON"
    const val INTRO_MOTIVATION_PRIVACY_SCREEN_NEXT_BUTTON = "INTRO_MOTIVATION_PRIVACY_SCREEN_NEXT_BUTTON"
    const val INTRO_MOTIVATION_ENERGY_SCREEN_NEXT_BUTTON = "INTRO_MOTIVATION_ENERGY_SCREEN_NEXT_BUTTON"
    const val INTRO_BATTERY_OPTIMISATION_SCREEN_ENLIST_BUTTON = "INTRO_BATTERY_OPTIMISATION_SCREEN_ENLIST_BUTTON"
    const val INTRO_BATTERY_OPTIMISATION_SCREEN_START_BUTTON = "INTRO_BATTERY_OPTIMISATION_SCREEN_START_BUTTON"


}